### ISSUE TITLE
[FEAT] 기초세팅

### ISSUE THREAD

**Issue by lhb8106** [TEAM-PLAYTOGETHER/PlayTogether_Android#1]
## 💫 Issue

프로젝트 초기세팅을 합니다.

## 📝 To-do
- [x] BaseActivity, Fragment 추가
- [x] 모듈 분리
- [x] kts로 수정
- [x] 라이브러리 추가
- [x] DI 세팅
- [x] 패키지 구조(domain, data)
- [x] 테스트 코드 작성 및 확인
