### ISSUE TITLE
[FEAT] 데모데이 정원 QA 

### ISSUE THREAD

**Issue by garden0401** [TEAM-PLAYTOGETHER/PlayTogether_Android#129]
## 💫 Issue

데모데이 직전 QA

## 📝 To-do
- [x] 신청자 명단들이 안 보임
- [x] 내가 개설한 번개인데 -> 내가 신청한 번개에도 리스트로 올라감
- [x] 번개리스트 -> sortBy(CreatedAt)
