### ISSUE TITLE
[FIX] 메시지함 및 채팅 오류 수정

### ISSUE THREAD

**Issue by briandr97** [TEAM-PLAYTOGETHER/PlayTogether_Android#130]
## 💫 Issue
오류 수정해써여

## 📝 To-do
- [x] 채팅 창 상대방 채팅도 내 채팅으로 보이는 오류
- [x] 채팅 창 새로 고침 버튼 기능 활성화
- [x] 메시지함 새로고침 로티 추가
- [x] 메시지 길어지면 줄 벗어나는 오류 수정
