### ISSUE TITLE
[FEAT] 온보딩 동아리 개설

### ISSUE THREAD

**Issue by lhb8106** [TEAM-PLAYTOGETHER/PlayTogether_Android#141]
## 💫 Issue
온보딩 동아리 개설

## 📝 To-do
- [x] 바뀐 부분 수정
- [x] 온보딩 동아리 개설 뷰
- [x] 온보딩 동아리 개설 api
