### ISSUE TITLE
[FEAT] 홈 뷰 hot list / new list 

### ISSUE THREAD

**Issue by oxix97** [TEAM-PLAYTOGETHER/PlayTogether_Android#160]
## 📝 To-do
- [x] hot list 구현
- [x] new list 구현
- [x] list item click listener 구현
