### ISSUE TITLE
[FEAT] 온보딩 재접속 뷰

### ISSUE THREAD

**Issue by lhb8106** [TEAM-PLAYTOGETHER/PlayTogether_Android#178]
## 💫 Issue
온보딩 재접속 뷰

## 📝 To-do
- [ ] recyclerview adapter onclick
- [ ] crew id setting
- [ ] 해당 crew home으로 이동
