### ISSUE TITLE
[UI] 내가 신청한 번개 상세보기 레이아웃

### ISSUE THREAD

**Issue by garden0401** [TEAM-PLAYTOGETHER/PlayTogether_Android#19]
## 💫 Issue

번개 탭 상세보기 -> 내가 신청한 번개 상세보기

## 📝 To-do
- [x] 내가 신청한 번개 상세보기 레이아웃
- [x] 번개 참여자 아이템뷰
- [x] "신청을 취소할까요?" 다이어로그1
- [x] "신청 취소되었습니다." 다이어로그2

**Comment by garden0401** [comment]
내가 신청한 번개 상세 레이아웃 완료
