### ISSUE TITLE
[FEAT] 번개탭 바뀐 UI 적용 및 서버수정

### ISSUE THREAD

**Issue by garden0401** [TEAM-PLAYTOGETHER/PlayTogether_Android#190]
## 💫 Issue

번개탭 릴리즈 버전 1.0 UI 적용
신청한 번개/ 오픈한 번개 함께 뜨는 이슈 확인

## 📝 To-do
- [x] 번개탭 아이템뷰 UI
- [x] 번개탭 서버 변경
- [x] 번개탭 이슈 확인
- [x] 번개탭 empty뷰 추가
- [x] 번개탭 is_opened 상태 처리
