### ISSUE TITLE
[FIX] 동아리 입장하기 로직 수정

### ISSUE THREAD

**Issue by lhb8106** [TEAM-PLAYTOGETHER/PlayTogether_Android#216]
## 💫 Issue
동아리 입장하기 로직 수정

## 📝 To-do
- [x] 동아리 입장하기 로직 수정
- [x] 동아리 이름 버튼 활성화 재확인
- [x] 동아리 입장 수정
- [x] 동아리 코드 입력 분기처리
- [x] 로그인 시 이동되는 뷰 부분 확인
