### ISSUE TITLE
[FEAT] 번개 상세 뷰 클릭 이벤트

### ISSUE THREAD

**Issue by oxix97** [TEAM-PLAYTOGETHER/PlayTogether_Android#222]
## 📝 To-do
- [x] 쪽지 클릭 이벤트
- [x] 다이어로그 분기처리 이벤트
- [x] 수정/삭제 클릭 이벤트
- [x] 신청 취소
- [x] 찜 하기
