### ISSUE TITLE
[CHORE] CRYING QA

### ISSUE THREAD

**Issue by oxix97** [TEAM-PLAYTOGETHER/PlayTogether_Android#254]
## 📝 To-do
- [x] 구글 로그인을 선택할 경우, 현재 갖고있는 구글 계정 중 어느걸 사용할지 고른 다음에 바로 메인뷰로 가버립니다 -> 그래서 프로필, 동아리 코드 입력 스텝을 점프해버리네요!
- [x] 번개 개설시, 상세 설명 항목에서 200자 이상 입력 후, 완료 버튼을 누를 때 무한 로딩이 지속되는 이슈 -> 번개 200자 제한을 안해서 그런듯
- [x] 신청 완료 뷰, 또는 신청 완료한 번개 상세보기에서 참여자들 목록 중 참여자 프로필을 눌렀을 때 액션이 없습니다 -> Adapter에다가 click Listener를 달아야할듯 -> 기능은 달았으나 본인을 구별하는 조건이 없어 Preference에다가 userId를 저장해야할거같다.
- [x] 동아리 이름이 안뜬다 ? -> 어디에서 연결이 안되는지 확인해야 할 거 같다 -> 자동 로그인 문제로 로그아웃할때 preference정보를 초기화 시키면 해당 문제는 사라진다.
- [ ] 동의 항목 링크 연결 -> Notion링크 설정 -> 노션 문의
- [x] 글을 많이 입력해서인지… 중간에 공백이 생겨요.. 홈 카드에서도 뭔가 공백이 생겨요.. -> 정원센세가 나중에 수정해준다고 함
- [x] 신청 완료시 (2/ )와 같이 참여할 수 있는 인원 수가 공백 또는 0으로 표시됩니다 ->null 들어가있는거 어케 표시 하지? -> view 수정
- [x] 제목이 길 경우 메인뷰 카드에서 제목이 먹갈할 라벨에 가려요(잘린다고 해야하나..?) -> 라벨로 겹치지 않게 줄바꿈되어야한다고함 -> 뷰 수정
- [x] 홈 카드 날짜, 시간, 장소 사이 간격 설정이 안 되어 있습니다! -> 간격 설정 -> 뷰 수정
- [x] 리스트 카드 날짜 장소 인원 사이 “|”로 나눠져있어요
- [x] 번개 상세보기 사진이 첨부한 사이즈 그대로 사이즈만 줄어서 표시돼요 -> 정방형 + 라운드값 10으로 표시되어야 합니다! -> 이게 무슨 말인지? -> 기능 수정
- [x] 번개 리스트 카드 찜 하트 아이콘과 찜한 숫자가 왼쪽 기준으로 되어있어요! -> 오른쪽 마진 기준으로 맞춰주실 수 있으실까요..?ㅎㅎㅎ
- [x] 번개 카테고리와 HOT 사이 실선 양끝 마진이 없어요! -> 양끝 마진 20 있어야 합니다!
- [x] 신청한, 오픈한, 찜한 별로 엠티뷰 문구가 전달 드린 것과 달라요! -> 전달드린 문구들로 수정이 필요합니다!
- [ ] 동아리 이름이 길 때 텍스트가 잘려요! -> 동아리 이름이 길 때는 텍스트가 잘리지 않게 줄바꿈이 한 번 더 필요할 것 같습니다! -> 뷰 수정
