### ISSUE TITLE
[CHORE] QA반영

### ISSUE THREAD

**Issue by lhb8106** [TEAM-PLAYTOGETHER/PlayTogether_Android#270]
## 💫 Issue
QA반영합니다

## 📝 To-do
- [x] 닉네임 입력 시 키보드 올라가는데,, 수정하기 버튼에 지하철역 텍스트가 겹침
- [x] 동아리 개설 - 한 줄 소개 입력하고 키보드가 안 내려가요! 
- [x] 온보딩 중간에 뒤로가기 버튼 누를 경우 메인뷰로 이동합니다
- [ ] 버튼 부분 스트로크(외곽선)이 안 되어 있어요!(팝업) 확인하기
- [ ] 프로필 수정하기의 수정하기 버튼이 안눌려요
- [x] 내 프로필 수정하기에서 텍스트필드 선택하면 키보드와 ‘수정하기’ 버튼이 같이 올라옵니다! (이미지 첨부)
