### ISSUE TITLE
[CHORE] 아마 이게 마지막 수정

### ISSUE THREAD

**Issue by oxix97** [TEAM-PLAYTOGETHER/PlayTogether_Android#272]
## 📝 To-do

- [x] 구글 로그인 로직 수정
- [x] 자동 로그인 로직 테스트케이스 재점검
- [x] 번개 신청완료 클릭 이벤트 부여 ( 번개 상세뷰와 같이 타인 프로필 조회가능하도록 )
- [x] 번개 상세뷰 인원 설정했는데도 무한으로 표기되는 경우 검토
- [ ] 전체적으로 한번씩 SSG하기
- [x] 찜한 번개 반영
- [x] 번개 삭제시 리스트 변경 안됨 -> 먹갈할 탭
- [x] 홈탭에서 새로고침이 잘 안되는듯
