### ISSUE TITLE
[CHORE] 기능 QA 반영

### ISSUE THREAD

**Issue by garden0401** [TEAM-PLAYTOGETHER/PlayTogether_Android#276]
## 💫 Issue
기능 QA 반영

## 📝 To-do
- [x] 동아리 1개 있을 때 탈퇴할 경우 -> 동아리 추가 및 개설뷰로 이동
- [x] 상대방 프로필 이름 null값
- [x] 프로필 이미지 수정 후 즉시 반영

**Comment by garden0401** [comment]
완료 #246
