### ISSUE TITLE
[QA] 죽지도 않고 다시 돌아온 QA

### ISSUE THREAD

**Issue by oxix97** [TEAM-PLAYTOGETHER/PlayTogether_Android#289]
## 💫 Issue

#289

## 📝 To-do
- [ ] 최신순 찜 많은순 반영 안된다고 함 -> 반영이 안되고 데이터가 늘어남 2배로 submitList 때문인가
- [ ] HOT, NEW 이모지 추가 -> 확인 받고 작업해야지
- [x] HOT, NEW 간격이 다르다고함
- [ ] 미정.미정.미정 -> 날짜 미정, 장소 미정, 시간 미정
- [x] 무한대 표시 -> 인원 제한 없음
- [x] ++ 모든 부분에 마이페이지에서 설정한 이미지 사용해야할듯 -> 카카오 로그인 -> 카카오 프사, 구글 로그인 -> 구글 프로필 (종찬) default로 들어가 있는 상태, 수정 해도 default로 박혀 있는건 안 바뀜
