### ISSUE TITLE
[UI] 내가 오픈한 번개 상세보기 레이아웃

### ISSUE THREAD

**Issue by garden0401** [TEAM-PLAYTOGETHER/PlayTogether_Android#29]
## 💫 Issue

번개 탭 상세보기 -> 내가 오픈한 번개 상세보기

## 📝 To-do
- [x] 내가 오픈한 번개 상세보기 레이아웃
- [x] 수정/삭제 스피너
- [x] "게시글을 삭제할까요?" 다이어로그1
- [x] "게시글이 삭제되었습니다" 다이어로그2

**Comment by garden0401** [comment]
내가 오픈한 번개 상세보기 레이아웃 완료
