### ISSUE TITLE
[FEAT] 회원가입 아이디, 비밀번호 입력뷰 분기처리

### ISSUE THREAD

**Issue by lhb8106** [TEAM-PLAYTOGETHER/PlayTogether_Android#31]
## 💫 Issue
회원가입 아이디, 비밀번호 입력뷰 분기처리

## 📝 To-do
- [ ] 아이디 edittext 분기처리
- [ ] 비밀번호 edittext 분기처리 및 확인
- [ ] 버튼 하나 알럿 활용 또는 제작
- [ ] 버튼 활성화 분기처리
