### ISSUE TITLE
[CHORE] 기초세팅 코드 수정

### ISSUE THREAD

**Issue by lhb8106** [TEAM-PLAYTOGETHER/PlayTogether_Android#6]
## 💫 Issue
기초세팅 코드 수정

## 📝 To-do
- [x] baseFragment 코드 수정
- [x] kts 코드 수정
- [x] 그 외 변경 사항 다시 체크
